# Generated by Django 4.2.17 on 2025-01-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
